spring:
  application:
    name: elasticsearch-entity
  elasticsearch:
    rest:
      uris: http://localhost:9200
      connection-timeout: 10s
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
